---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - devpipeline.devpipeline.local
  resources:
  - devtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devpipeline.devpipeline.local
  resources:
  - devtasks/finalizers
  verbs:
  - update
- apiGroups:
  - devpipeline.devpipeline.local
  resources:
  - devtasks/status
  verbs:
  - get
  - patch
  - update
